export const medicationData = [
  {
    name: 'Adrenalin',
    group: 'Katecholamin',
    effect: 'Steigert Herzleistung, Vasokonstriktion, Bronchodilatation',
    indications: 'Reanimation, Anaphylaxie',
    sideEffects: 'Tachykardie, Arrhythmien',
    contraindications: 'Keine absoluten bei vitaler Bedrohung',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Amiodaron',
    group: 'Antiarrhythmikum',
    effect: 'Stabilisiert Herzrhythmus',
    indications: 'VF/pVT, Tachyarrhythmien',
    sideEffects: 'Hypotonie, Bradykardie',
    contraindications: 'Jodallergie relativ',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Atropin',
    group: 'Parasympatholytikum',
    effect: 'Erhoeht Herzfrequenz',
    indications: 'Bradykardie',
    sideEffects: 'Tachykardie, Mundtrockenheit',
    contraindications: 'Engwinkelglaukom relativ',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Adenosin',
    group: 'Antiarrhythmikum',
    effect: 'Kurzzeitiger AV-Block',
    indications: 'SVT',
    sideEffects: 'Brustdruck, Dyspnoe',
    contraindications: 'AV-Block hoehergradig',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Noradrenalin',
    group: 'Vasopressor',
    effect: 'Vasokonstriktion',
    indications: 'Schock',
    sideEffects: 'Ischaemien, Hypertonie',
    contraindications: 'Unbehandelte Hypovolaemie',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Dobutamin',
    group: 'Inotropikum',
    effect: 'Steigert Kontraktilitaet',
    indications: 'Kardiogener Schock',
    sideEffects: 'Tachykardie',
    contraindications: 'Hypertrophe Kardiomyopathie',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'ASS',
    group: 'Thrombozytenhemmer',
    effect: 'Hemmt Plaettchenaggregation',
    indications: 'ACS',
    sideEffects: 'Blutungen',
    contraindications: 'Aktive Blutung',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Heparin',
    group: 'Antikoagulans',
    effect: 'Gerinnungshemmung',
    indications: 'ACS, Thrombosen',
    sideEffects: 'Blutungen',
    contraindications: 'Aktive Blutung',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Nitroglycerin',
    group: 'Vasodilatator',
    effect: 'Vorlastsenkung',
    indications: 'ACS, Lungenoedem',
    sideEffects: 'Hypotonie',
    contraindications: 'Schwere Hypotonie',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Morphin',
    group: 'Opioid',
    effect: 'Analgesie',
    indications: 'Starke Schmerzen',
    sideEffects: 'Atemdepression',
    contraindications: 'Schwere Ateminsuffizienz',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Nalbuphin',
    group: 'Opioid-Analgetikum',
    category: 'Analgesie',
    subcategory: 'Opioide',
    effect:
      'Analgetisch, sedierend, geringere Atemdepression im Vergleich zu vielen klassischen Opioiden; wirkt insbesondere ueber Kappa-Opioidrezeptoren.',
    indications:
      'Mittelstarke bis starke akute Schmerzen, traumatische Verletzungen, Frakturen, Verbrennungen, kolikartige Schmerzen, praeklinische Schmerztherapie im Rettungsdienst.',
    sideEffects:
      'Schwindel, Muedigkeit, Sedierung, Uebelkeit, Erbrechen, Schwitzen, Blutdruckabfall, Bradykardie selten, Atemdepression deutlich seltener als bei klassischen Opioiden.',
    contraindications:
      'Bekannte Ueberempfindlichkeit gegen Nalbuphin, schwere Leberinsuffizienz, schwere Ateminsuffizienz, Vorsicht bei opioidabhaengigen Patienten wegen moeglicher Entzugssymptome.',
    applicationRoutes: 'Intravenoes (i.v.), intramuskulaer (i.m.), subkutan (s.c.)',
    specialNotes:
      'Gute Analgesie bei vergleichsweise geringem Risiko schwerer Atemdepression. Kann die Wirkung anderer Opioide abschwaechen und bei opioidabhaengigen Patienten Entzugssymptome ausloesen. Kontinuierliches Monitoring von Bewusstsein, Atmung und Kreislauf empfohlen.',
    monitoring: 'SpO2, Atemfrequenz, Blutdruck, Herzfrequenz, Bewusstseinslage, Schmerzskala (NRS)',
    sopLink: 'Platzhalter fuer regionale SOP Region Hannover',
    nunLink: 'Platzhalter fuer entsprechende NUN-Algorithmen',
    tags: 'Analgesie, Schmerztherapie, Opioid, Trauma, Fraktur, Verbrennung, Rettungsdienst',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Fentanyl',
    group: 'Opioid',
    effect: 'Starke Analgesie',
    indications: 'Trauma, starke Schmerzen',
    sideEffects: 'Atemdepression',
    contraindications: 'Vorsicht bei Ateminsuffizienz',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Ketamin',
    group: 'Dissoziativum',
    effect: 'Analgesie und Sedierung',
    indications: 'Trauma, Analgesie',
    sideEffects: 'Halluzinationen',
    contraindications: 'Relative KI bei Psychosen',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Esketamin',
    group: 'Dissoziativum',
    effect: 'Analgesie',
    indications: 'Starke Schmerzen',
    sideEffects: 'Blutdruckanstieg',
    contraindications: 'Relative KI Psychosen',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Metamizol',
    group: 'Nichtopioid',
    effect: 'Analgesie, antipyretisch',
    indications: 'Schmerzen, Koliken',
    sideEffects: 'Hypotonie',
    contraindications: 'Fruehere Agranulozytose',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Paracetamol',
    group: 'Analgetikum',
    effect: 'Analgetisch',
    indications: 'Schmerz, Fieber',
    sideEffects: 'Lebertoxizitaet',
    contraindications: 'Schwere Lebererkrankung',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Ibuprofen',
    group: 'NSAR',
    effect: 'Entzuendungshemmend',
    indications: 'Schmerz, Fieber',
    sideEffects: 'GI-Blutung',
    contraindications: 'Ulkus, Blutung',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Midazolam',
    group: 'Benzodiazepin',
    effect: 'Sedierend, antikonvulsiv',
    indications: 'Krampfanfall',
    sideEffects: 'Atemdepression',
    contraindications: 'Vorsicht Ateminsuffizienz',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Diazepam',
    group: 'Benzodiazepin',
    effect: 'Antikonvulsiv',
    indications: 'Krampfanfall',
    sideEffects: 'Atemdepression',
    contraindications: 'Schwere Ateminsuffizienz',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Lorazepam',
    group: 'Benzodiazepin',
    effect: 'Antikonvulsiv',
    indications: 'Krampfanfall',
    sideEffects: 'Sedierung',
    contraindications: 'Ateminsuffizienz',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Propofol',
    group: 'Hypnotikum',
    effect: 'Sedierung',
    indications: 'Narkose',
    sideEffects: 'Hypotonie',
    contraindications: 'Kreislaufinstabilitaet',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Etomidat',
    group: 'Hypnotikum',
    effect: 'Kurze Sedierung',
    indications: 'Narkoseeinleitung',
    sideEffects: 'Nebennierenhemmung',
    contraindications: 'Ueberempfindlichkeit',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Levetiracetam',
    group: 'Antikonvulsivum',
    effect: 'Krampfunterdrueckung',
    indications: 'Krampfanfall',
    sideEffects: 'Muedigkeit',
    contraindications: 'Ueberempfindlichkeit',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Salbutamol',
    group: 'Beta-2-Mimetikum',
    effect: 'Bronchodilatation',
    indications: 'Asthma, COPD',
    sideEffects: 'Tachykardie',
    contraindications: 'Keine wesentlichen absoluten',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Ipratropium',
    group: 'Anticholinergikum',
    effect: 'Bronchodilatation',
    indications: 'COPD, Asthma',
    sideEffects: 'Mundtrockenheit',
    contraindications: 'Ueberempfindlichkeit',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Prednisolon',
    group: 'Glukokortikoid',
    effect: 'Entzuendungshemmung',
    indications: 'Asthma, Anaphylaxie',
    sideEffects: 'Hyperglykaemie',
    contraindications: 'Keine relevanten Notfall-KI',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Methylprednisolon',
    group: 'Glukokortikoid',
    effect: 'Entzuendungshemmung',
    indications: 'Asthma, Anaphylaxie',
    sideEffects: 'Hyperglykaemie',
    contraindications: 'Keine relevanten Notfall-KI',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Magnesiumsulfat',
    group: 'Elektrolyt',
    effect: 'Membranstabilisierung',
    indications: 'Torsade, Asthma',
    sideEffects: 'Hypotonie',
    contraindications: 'AV-Block relativ',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Dimetinden',
    group: 'Antihistaminikum',
    effect: 'H1-Blockade',
    indications: 'Allergie',
    sideEffects: 'Muedigkeit',
    contraindications: 'Ueberempfindlichkeit',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Clemastin',
    group: 'Antihistaminikum',
    effect: 'H1-Blockade',
    indications: 'Anaphylaxie',
    sideEffects: 'Sedierung',
    contraindications: 'Ueberempfindlichkeit',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Naloxon',
    group: 'Antidot',
    effect: 'Hebt Opioidwirkung auf',
    indications: 'Opioidintoxikation',
    sideEffects: 'Entzugssymptome',
    contraindications: 'Keine relevanten',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Flumazenil',
    group: 'Antidot',
    effect: 'Hebt Wirkung auf',
    indications: 'Benzodiazepinintoxikation',
    sideEffects: 'Krampfanfaelle',
    contraindications: 'Epilepsie relativ',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Glucose',
    group: 'Kohlenhydrat',
    effect: 'Blutzuckeranstieg',
    indications: 'Hypoglykaemie',
    sideEffects: 'Hyperglykaemie',
    contraindications: 'Keine',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Glucagon',
    group: 'Hormon',
    effect: 'Mobilisiert Glucose',
    indications: 'Hypoglykaemie',
    sideEffects: 'Uebelkeit',
    contraindications: 'Phaeochromozytom',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Ondansetron',
    group: 'Antiemetikum',
    effect: '5-HT3-Blockade',
    indications: 'Uebelkeit',
    sideEffects: 'QT-Verlaengerung',
    contraindications: 'QT-Syndrom',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Dimenhydrinat',
    group: 'Antiemetikum',
    effect: 'Antihistaminisch',
    indications: 'Uebelkeit',
    sideEffects: 'Muedigkeit',
    contraindications: 'Engwinkelglaukom',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'MCP',
    group: 'Antiemetikum',
    effect: 'Prokinetisch',
    indications: 'Uebelkeit',
    sideEffects: 'EPS',
    contraindications: 'Morbus Parkinson',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Tranexamsaeure',
    group: 'Antifibrinolytikum',
    effect: 'Gerinnselstabilisierung',
    indications: 'Blutung',
    sideEffects: 'Thromboserisiko',
    contraindications: 'Aktive Thrombose relativ',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Oxytocin',
    group: 'Uterotonikum',
    effect: 'Uteruskontraktion',
    indications: 'Postpartale Blutung',
    sideEffects: 'Hypotonie',
    contraindications: 'Ueberempfindlichkeit',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Nifedipin',
    group: 'Calciumantagonist',
    effect: 'Vasodilatation',
    indications: 'Hypertonie',
    sideEffects: 'Hypotonie',
    contraindications: 'Schock',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Hydroxocobalamin',
    group: 'Antidot',
    effect: 'Bindet Cyanid',
    indications: 'Cyanidintoxikation',
    sideEffects: 'Hautroetung',
    contraindications: 'Keine relevanten',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Natriumhydrogencarbonat',
    group: 'Puffer',
    effect: 'Pufferung',
    indications: 'Hyperkaliaemie, Intox',
    sideEffects: 'Alkalose',
    contraindications: 'Alkalose',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
  {
    name: 'Calciumgluconat',
    group: 'Elektrolyt',
    effect: 'Membranstabilisierung',
    indications: 'Hyperkaliaemie',
    sideEffects: 'Gewebsreizung',
    contraindications: 'Hyperkalzaemie',
    appNote: 'SOP- und NUN-Verknuepfung spaeter ergaenzen.',
  },
]
